name: "Generate release assets"

on:
  push:
    tags:
      - "ktls-utils-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Install dependencies"
      run: |
        sudo apt-get update
        sudo apt-get -y install gnutls-dev libkeyutils-dev libnl-3-dev libnl-genl-3-dev

    - name: "Instantiate autotools"
      run: ./autogen.sh

    - name: "Configure build environment"
      run: ./configure --with-systemd

    - name: "Build release asset"
      run: make dist

    - name: "Version"
      run: |
        echo "ktls_utils_version=`./configure --version | awk '{print $3;; exit}'`" >> $GITHUB_ENV

    - name: "Create release"
      uses: actions/create-release@latest
      id: create_release
      with:
        body_path: NEWS
        release_name: v${{ env.ktls_utils_version }}
        tag_name: ${{ github.ref }}
        prerelease: false
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "Upload release tarball"
      uses: actions/upload-release-asset@latest
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ktls-utils-${{ env.ktls_utils_version }}.tar.gz
        asset_name: ktls-utils-${{ env.ktls_utils_version }}.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
